FROM node:18 AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install

# Copy rest of the files only after dependencies install
COPY .env .env
COPY . .

# Show build output even if it fails
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]